### PR TITLE
Add pitfalls icon

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Adding the pitfalls icon. I did run the SVG through an optimizer already as well. 

Original issue is in the hint repo: https://github.com/webhintio/hint/issues/1777

### CODE REVIEW

**Comment by molant** [comment]
@sarvaje does this need to go into the HTML formatter?

**Comment by sarvaje** [comment]
I think this should go to the [`html-formatter`](https://github.com/webhintio/hint/tree/master/packages/formatter-html/src/assets/images/scan)

**Comment by ststimac** [comment]
So I should open a PR with the image added over here: https://github.com/webhintio/hint/tree/master/packages/formatter-html/src/assets ?

**Comment by sarvaje** [comment]
>So I should open a PR with the image added over here: https://github.com/webhintio/hint/tree/master/packages/formatter-html/src/assets

Yes, please.

**Comment by molant** [comment]
> So I should open a PR with the image added over here:

Yes, we will probably add some stuff on top of your PR to enable it.

Thanks!

**Pull request closed without merging**
