### PR TITLE
Fix: OpenJSF header text color

### PR DESCRIPTION
**Pull request by kborchers**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Non-link text in the OpenJSF header outside of the home page need to be explicitly set to white

### CODE REVIEW

**Comment by kborchers** [comment]
No problem. Sorry I missed it the first time. I think I was so focused on the logo in the footer I forgot to check the header on other pages.

**Comment by sarvaje** [comment]
@antross visually there is no changes. I suppose this is only to be sure the text in the header is white, and nothing else change it color, right?

**Comment by kborchers** [comment]
@sarvaje when I look at pages other than the home page, the text outside of the link is black without this fix

**Comment by sarvaje** [comment]
> @sarvaje when I look at pages other than the home page, the text outside of the link is black without this fix

Interesting... hehehe

I was testing only the home page...

**Pull request merged**
