### PR TITLE
Updates website header

### PR DESCRIPTION
**Pull request by hxlnt**
Addresses #766.

### CODE REVIEW

**Comment by molant** [comment]
We also need to update the `About` links and add an entry for `Project Charter`. If it can be done in this PR it would be great, if not I'll look into it as soon as I have some free time 😊

**Comment by hxlnt** [comment]
@antross 's comment gave me the idea to split these out into "Try" (online scanner) and "Install" (extensions + CLI). This shortens up the header and helps give newcomers a better idea of the intent behind the online scanner. See latest commit.

@molant To add the Project Charter, we'd probably also want to update the About landing page and get new icons in place, right? So maybe better to split into a separate PR?

image

**Comment by molant** [comment]
> So maybe better to split into a separate PR?

We can probably add it to the menu and open an issue to add the icon in the landing page later. I don't think we link to "/about" from any place, it's just a placeholder in case someone navigates manually there. The reason is that I don't know when we will have an icon and linking to it is part of the requirements of the OpenJS Foundation.

**Comment by hxlnt** [comment]
Now that `npm install` is working again (thanks, @molant!), I was able to build the site locally to test changes and add a link to the project charter. New changes include a tweak to logic in `headers.ejs` and an additional entry in the About section.

screenshot1

screenshot2

screenshot3

**Comment by molant** [comment]
@hxlnt do you know why the title is duplicated in the charter?

**Comment by hxlnt** [comment]
@molant Good catch, looks like there were some custom rules in the CSS to hide headers. Fixed.

**Pull request merged**
