### PR TITLE
Fix: cache busting service worker

### PR DESCRIPTION
**Pull request by qzhou1607**
## Pull request checklist

Make sure you:

- [X] Signed the [Contributor License Agreement](https://cla.js.foundation/sonarwhal/sonarwhal)
- [X] Followed the [commit message guidelines](https://sonarwhal.com/docs/contributor-guide/contributing/pull-requests/#commitmessages)

## Short description of the change(s)
1. Cache busting service worker (#362 )
2. Currently the `service worker` caches `sw-reg.js` as well. Remove that from the list of files being cached.

Btw, `generate service worker` has to happen after `build:hexo` otherwise it can't get the right list of `.html` files in the service worker. And the script has to be in the root directory otherwise the scope isn't right. So instead of copying the scripts to `static/scripts`, I write its own gulp task. 

I also tried moving all `rev` and `revplace` tasks **after** `build:hexo`, hoping that we don't need to have to separate tasks for rev themes, md files and service worker that way. But `sw-reg` keeps reporting `redundant` service workers and I had trouble figuring out why. So I kept the task order as it was, I'm switching to the next task now but let me know if you'd like me to keep digging on this route.

### CODE REVIEW

**Comment by qzhou1607** [comment]
@molant I think moving the service worker files to `/static/scripts` will result in scope issues. According to [this](https://stackoverflow.com/a/35415127) answer, the **max** scope of a service worker is where it's located (in our case `/static/scripts`), so unless we can change the `Service-Worker-Allowed` header when serving service workers, we can't use the service worker for images (`/static/images`) or css (`/static/styles`).

**Comment by molant** [comment]
@qzhou1607 that's what I though initially but I remember reading somewhere that it was scoped to were the registration was happening or under. Can't seem to find the link.

**Comment by molant** [comment]
Can you double check the behavior in both scenarios?

**Comment by molant** [comment]
> It does seem the location of the service worker script matters.

😫

Can you then please take a look at https://jakearchibald.com/2016/caching-best-practices/ and make sure that we are doing the recommendations for Service Workers and how to access the resources (network first for HTML, cache first for static resources, and I don't know if something else)?

**Comment by qzhou1607** [comment]
@molant I read the blog again, we are definitely doing the right thing for accessing the resources, including:
* Cache busting the assets (images, stylesheets, scripts), change the url if there are updates.
* Always revalidate the HTML pages

It didn't mention anything about the right thing to do about `sw-reg` and `service worker` scripts themselves. I think what we do so far is correct, as long as the followings are satisfied:

* Cache busting the `sw-reg` and `sonarwhal-worker`. If there is a change in the service worker, it's reflected in the file name.
* Make sure to always revalidate the HTML pages linking to `sw.reg.js`. This way, the latest service worker is registered.
* A `max-age` can now be set on the service worker and registration scripts, since updates are reflected by changes in the filenames.
* Based on my investigation so far, we have to keep the service worker script in the root due to the scope. Alternatively, we can use the `Service Worker Allowed` header to override the scope like in [this](https://stackoverflow.com/questions/35358038/how-to-register-a-service-workers-scope-one-directory-above-where-the-service-w/35415127#35415127) post. Or just figure out a way to change the `cache control` header of the service scripts in the root without moving them to `/static/scripts`.

**Comment by molant** [comment]
I think I'd rather change the `max-age` than sending the extra header.


Is there a way where we can tell the SW to go to the network first for all `.html` requests and to serve the cache first for the rest? This should probably avoid the issues we've been having with content not being fresh.

Also, our links don't end up in `.html` so we need to make sure to be intercepting those requests and serve the right asset.

**Comment by qzhou1607** [comment]
@molant Currently the `cache-control` headers of the HTML pages are set to `no-cache`, with that the html content will always be revalidated with the server before serving from the cache, right? I don't think we need to control that from the service worker.

> Is there a way where we can tell the SW to go to the network first for all .html requests and to serve the cache first for the rest? This should probably avoid the issues we've been having with content not being fresh.

Did you mean the links to `sw-reg,js`? I'm confused - why is it not in `.html`?
>Also, our links don't end up in .html so we need to make sure to be intercepting those requests and serve the right asset

**Comment by molant** [comment]
> Did you mean the links to `sw-reg,js`? I'm confused - why is it not in `.html`?

E.g.:
We are always using `/docs/user-guide/` but the value key we are using to store the HTML it in the cache is `/docs/user-guide/index.html`

> with that the html content will always be revalidated with the server before serving from the cache, right? I don't think we need to control that from the service worker.

I'm almost sure the SW is going to intercept that request regardless of what the header says, otherwise how would offline experiences work?

**Comment by alrra** [comment]
We don't have a SW anymore, so closing this for now.

**Pull request closed without merging**
