### PR TITLE
Breaking: Update `Interoperability` to `Compatibility`

### PR DESCRIPTION
**Pull request by molant**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Update all mentions of `interoperability` to `compatibility` 

Ref webhintio/hint#1507

### CODE REVIEW

**Comment by molant** [comment]
Please review but don't merge until there's a plan to roll out the change in all the instances.

**Comment by sarvaje** [comment]
The fact that we need to sync the merge with the web and the online-service is not a signal to mark this PR as `Breaking:`?

**Comment by molant** [comment]
@sarvaje probably, see https://github.com/webhintio/hint/pull/1687#issuecomment-454509974

**Comment by sarvaje** [comment]
> @sarvaje probably, see webhintio/hint#1687 (comment)

ahhh hehehe, I didn't see that :)

**Comment by molant** [comment]
PR is failing because we [need to merge the `hint` one first.](https://github.com/webhintio/hint/pull/1687)

**Pull request merged**
