### PR TITLE
Update home page with new content

### LINKED ISSUE #765: Update homepage to include VS Code and browser extensions
Copy updates are in #764

### PR DESCRIPTION
**Pull request by ststimac**
## Pull request checklist

Make sure you:

- [x] Signed the [Contributor License Agreement](https://cla.js.foundation/webhintio/webhint.io)
- [x] Followed the [commit message guidelines](https://webhint.io/docs/contributor-guide/getting-started/pull-requests/#commit-messages)

## Short description of the change(s)

Fixes #765 **and** #762 

Updates home page with new content

There's still one illustration we're missing. I've commented where that needs to go. I wanted to submit this PR so that I'm not blocking getting the home page updated since I'll be largely unavailable/sporadically online for the next few days. 

I'm trying to take a screenshot of the page but my extension for doing so doesn't work on localhost. Hrmm.

### CODE REVIEW

**Comment by ststimac** [comment]
Screen Shot 2019-09-24 at 12 46 30 PM
Screen Shot 2019-09-24 at 12 46 37 PM

**Comment by molant** [comment]
> There's still one illustration we're missing.

I just sent it to you.

**Comment by ststimac** [comment]
Alright, adding the illustration now. :P

**Comment by ststimac** [comment]
Screen Shot 2019-09-24 at 12 54 32 PM

**Comment by ststimac** [comment]
Screen Shot 2019-09-24 at 1 27 00 PM

**Comment by hxlnt** [comment]
Looks great to me! :) Thanks!

**Comment by antross** [comment]
@sarvaje Doesn't look like that tool makes the SVGs meaningfully smaller (only saves less than 1KB on each)

**Comment by sarvaje** [comment]
ok

**Pull request merged**
